const eventsDatabase = [
  {
    "id": 22,
    "title": "مهرجان رمضان الخيري – سفراء الخير",
    "year": "2026",
    "date": "رمضان 2026",
    "desc": "مهرجان سفراء الخير الرمضاني للعمل الخيري وتوزيع المساعدات.",
    "cat": "charity",
    "tagLabel": "العمل الخيري",
    "img": "/events/Ramadan 2025/WhatsApp Image 2025-03-11 at 19.11.48_f43ac744.jpg",
    "dotColor": "orange"
  },
  {
    "id": 21,
    "title": "رحلة العين السخنة والقاهرة",
    "year": "2025",
    "date": "24/10/2025",
    "desc": "رحلة ترفيهية شاملة إلى العين السخنة وكايرو فيستيفال سيتي.",
    "cat": "trips",
    "tagLabel": "رحلات",
    "img": "/events/scraped/70-2.jpg",
    "dotColor": "teal"
  },
  {
    "id": 20,
    "title": "حملة إغاثة غزة مع رسالة الدقهلية",
    "year": "2023",
    "date": "2023/2024",
    "desc": "تجهيز وتعبئة المساعدات الإنسانية لأهالي غزة بالتعاون مع جمعية رسالة بالدقهلية.",
    "cat": "charity",
    "tagLabel": "العمل الخيري",
    "img": "/events/Ramadan 2024/WhatsApp Image 2024-03-14 at 18.32.52_37a830e9.jpg",
    "dotColor": "orange"
  },
  {
    "id": 19,
    "title": "المعرض الخيري السنوي الثاني",
    "year": "2023",
    "date": "2023",
    "desc": "إعداد وتنظيم المعرض الخيري السنوي الثاني للملابس.",
    "cat": "charity",
    "tagLabel": "العمل الخيري",
    "img": "/events/المعرض الخيري الثانى/WhatsApp Image 2023-11-04 at 11.56.29 PM.jpeg",
    "dotColor": "orange"
  },
  {
    "id": 18,
    "title": "توزيع كراتين رمضان",
    "year": "2023",
    "date": "رمضان 2023",
    "desc": "توزيع كراتين رمضان على عمال جامعة حورس.",
    "cat": "charity",
    "tagLabel": "العمل الخيري",
    "img": "/events/Ramadan 2023/1.jpg",
    "dotColor": "orange"
  },
  {
    "id": 17,
    "title": "تنظيم مؤتمر AIRGEC 23",
    "year": "2023",
    "date": "2023",
    "desc": "رعاية وتنظيم المؤتمر العلمي الدولي AIRGEC 2023.",
    "cat": "conf",
    "tagLabel": "مؤتمرات",
    "img": "/events/Architectura department honorary event/IMG_9767.jpg",
    "dotColor": "teal"
  },
  {
    "id": 16,
    "title": "تنظيم ملتقى التوظيف الأول",
    "year": "2023",
    "date": "2023",
    "desc": "تنظيم ورعاية أول ملتقى توظيفي بكلية الهندسة بمشاركة كبرى الشركات.",
    "cat": "conf",
    "tagLabel": "مؤتمرات",
    "img": "/events/scraped/428046797_8140837339276126_1539665425403559252_n.jpg",
    "dotColor": "teal"
  },
  {
    "id": 15,
    "title": "بوم بوم داي 2",
    "year": "2023",
    "date": "2023",
    "desc": "النسخة الثانية من مهرجان بوم بوم داي السنوي.",
    "cat": "campus",
    "tagLabel": "حياة جامعية",
    "img": "/events/scraped/84.jpg",
    "dotColor": "gold"
  },
  {
    "id": 14,
    "title": "مسابقة أفضل أسرة طلابية",
    "year": "2023",
    "date": "2023",
    "desc": "الفوز بالمركز الأول كأفضل أسرة طلابية في الأنشطة الجامعية واستلام درع التفوق.",
    "cat": "campus",
    "tagLabel": "حياة جامعية",
    "img": "/Ambassadors Photos/IMG-20230710-WA0198.jpg",
    "dotColor": "gold"
  },
  {
    "id": 13,
    "title": "رحلات وزارة الشباب والرياضة – الأقصر وأسوان",
    "year": "2022/23",
    "date": "2022/2023",
    "desc": "المشاركة في رحلة قطار الشباب إلى الأقصر وأسوان بالتعاون مع وزارة الشباب والرياضة.",
    "cat": "trips",
    "tagLabel": "رحلات",
    "img": "/Ambassadors Photos/WhatsApp Image 2023-12-24 at 00.47.06_45888772.jpg",
    "dotColor": "teal"
  },
  {
    "id": 12,
    "title": "احتفالية رأس السنة – ممشى أهل مصر",
    "year": "2022/23",
    "date": "2022/2023",
    "desc": "احتفالية رأس السنة ورحلة مميزة إلى ممشى أهل مصر بالقاهرة.",
    "cat": "trips",
    "tagLabel": "رحلات",
    "img": "/events/scraped/81.jpg",
    "dotColor": "teal"
  },
  {
    "id": 11,
    "title": "رحلة العين السخنة",
    "year": "2022",
    "date": "2022",
    "desc": "رحلة ترفيهية استجمامية إلى العين السخنة.",
    "cat": "trips",
    "tagLabel": "رحلات",
    "img": "/events/scraped/70-2.jpg",
    "dotColor": "teal"
  },
  {
    "id": 10,
    "title": "رحلة دريم بارك – القاهرة",
    "year": "2022",
    "date": "2022",
    "desc": "رحلة ترفيهية إلى مدينة الألعاب دريم بارك بالقاهرة.",
    "cat": "trips",
    "tagLabel": "رحلات",
    "img": "/events/scraped/80.jpg",
    "dotColor": "teal"
  },
  {
    "id": 9,
    "title": "تزيين كلية الهندسة في رمضان",
    "year": "2022",
    "date": "رمضان 2022",
    "desc": "تزيين كلية الهندسة بأجواء رمضانية وإنشاء منطقة تصوير مخصصة.",
    "cat": "campus",
    "tagLabel": "حياة جامعية",
    "img": "/events/Ramadan Decoration 2022/WhatsApp Image 2023-11-04 at 2.22.40 AM (1).jpeg",
    "dotColor": "gold"
  },
  {
    "id": 8,
    "title": "الإفطار الرمضاني السنوي",
    "year": "2022",
    "date": "رمضان 2022",
    "desc": "الإفطار الرمضاني السنوي لأسرة سفراء حورس لجمع الأعضاء على مائدة واحدة.",
    "cat": "campus",
    "tagLabel": "حياة جامعية",
    "img": "/events/Ramadan iftar 2022/IMG-20220419-WA0004.jpg",
    "dotColor": "gold"
  },
  {
    "id": 7,
    "title": "بوم بوم داي 1",
    "year": "2022",
    "date": "2022",
    "desc": "أول نسخة من بوم بوم داي داخل الجامعة على مدار أربعة أيام، شملت مطاعم، ألعاب، ودي جي.",
    "cat": "campus",
    "tagLabel": "حياة جامعية",
    "img": "/Ambassadors Photos/IMG-20230710-WA0192.jpg",
    "dotColor": "gold"
  },
  {
    "id": 6,
    "title": "يوم الهندسة / استقبال الطلاب الجدد",
    "year": "2021/22",
    "date": "2021/2022",
    "desc": "تنظيم يوم الهندسة الأول، وتعريف الطلاب الجدد وأولياء الأمور بالأقسام والمعامل.",
    "cat": "campus",
    "tagLabel": "حياة جامعية",
    "img": "/events/Reception day  2026/IMG-20250921-WA0015.jpg",
    "dotColor": "gold"
  },
  {
    "id": 5,
    "title": "المعرض الخيري لجامعة حورس",
    "year": "2022",
    "date": "2022",
    "desc": "تنظيم المعرض الخيري السنوي، تجميع وتجهيز الملابس وبيعها بأسعار رمزية.",
    "cat": "charity",
    "tagLabel": "العمل الخيري",
    "img": "/events/المعرض الخيري الثانى/WhatsApp Image 2023-11-05 at 2.56.30 AM.jpeg",
    "dotColor": "orange"
  },
  {
    "id": 4,
    "title": "زيارة دار مسنين أهالينا – رسالة المنصورة",
    "year": "2022",
    "date": "2022",
    "desc": "زيارة دار أهالينا للمسنين بالتعاون مع جمعية رسالة بالمنصورة، وتوزيع الهدايا ودرع التكريم.",
    "cat": "charity",
    "tagLabel": "العمل الخيري",
    "img": "/events/Ramadan Decoration 2022/WhatsApp Image 2023-11-04 at 2.22.40 AM (1).jpeg",
    "dotColor": "orange"
  },
  {
    "id": 3,
    "title": "تكريم الفائزين بمسابقة العمارة",
    "year": "2021/22",
    "date": "2021/2022",
    "desc": "تكريم الفائزين في مسابقة قسم الهندسة المعمارية.",
    "cat": "campus",
    "tagLabel": "حياة جامعية",
    "img": "/events/Architectura department honorary event/IMG_9810.jpg",
    "dotColor": "gold"
  },
  {
    "id": 2,
    "title": "قافلة خيرية لقرى دمياط",
    "year": "2021/22",
    "date": "2021/2022",
    "desc": "قافلة خيرية لتوزيع المساعدات على القرى الفقيرة بمحافظة دمياط.",
    "cat": "charity",
    "tagLabel": "العمل الخيري",
    "img": "/events/المعرض الخيري الثانى/WhatsApp Image 2023-11-04 at 10.03.40 PM.jpeg",
    "dotColor": "orange"
  },
  {
    "id": 1,
    "title": "توزيع كراتين رمضان",
    "year": "2021",
    "date": "رمضان 2021",
    "desc": "توزيع كراتين رمضان على العمال وأفراد الأمن بجامعة حورس وكلية الهندسة.",
    "cat": "charity",
    "tagLabel": "العمل الخيري",
    "img": "/events/Ramadan 2022/horus ambassadors ramadan.jpg",
    "dotColor": "orange"
  }
];
